name: Help_Dev_Build 
on:
    push:
        branches:
            - '*'
            - '!main'

jobs:
  mkdocs:
    name: Build and deploy mkdocs site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        source $HOME/.poetry/env
        poetry shell
        mkdocs build

    # - uses: thomasattree/mkdocs2S3@master
    #   with:
    #     args: --acl public-read --follow-symlinks --delete
    #   env:
    #     AWS_S3_BUCKET: helpdev.biodati.com
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
    #     SOURCE_DIR: 'site'      # optional: defaults to entire repository

    # - name: Build
    #   uses: jnanadarshan/mkdocs-build-action@v0.24

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Sync output to S3
      run: |
        aws s3 sync ./site/ s3://helpdev.biodati.com --delete

    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '*Deployment to HelpDev.biodati.com*'
        mention_if: 'success'
        channel: '#devops'
        url: ${{ secrets.SLACK_DEVOPS_WEBHOOK }}

